[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  
[dev]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200